config/routes.rb
Rails.application.routes.draw do
  get 'publishers/new'

  get 'publishers/create'

  get 'publishers/update'

  get 'publishers/edit'

  get 'publishers/destroy'

  get 'publishers/index'

  get 'publishers/show'

  get 'authors/new'

  get 'authors/create'

  get 'authors/update'

  get 'authors/edit'

  get 'authors/destroy'

  get 'authors/index'

  get 'authors/show'

  get 'categories/new'

  get 'categories/create'

  get 'categories/update'

  get 'categories/edit'

  get 'categories/destroy'

  get 'categories/index'

  get 'categories/show'

  get 'books/new'

  get 'books/create'

  get 'books/update'

  get 'books/edit'

  get 'books/destroy'

  get 'books/index'

  get 'books/show'

  get 'about' => "about#index"

  root 'books#index'

  resources :books
  resources :authors
  resources :categories
  resources :publishers
  

end

app/models/author.rb
class Author < ActiveRecord::Base
	has_many :books
	validates_presence_of :first_name
	validates_presence_of :last_name
end

app/models/book.rb
class Book < ActiveRecord::Base
	belongs_to :category
	belongs_to :author
	belongs_to :publisher

	validates_presence_of :title
end


# , :category_id, :author_id, :publisher_id, :isbn, :buy, :price, :format, :excerpt, :pages, :year

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :books

	validates :name, presence: true, length: {minimum: 3}
end

app/models/publisher.rb
class Publisher < ActiveRecord::Base
	has_many :books
	validates_presence_of :name, length: {minimum:3}
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  	@page_title = 'About'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def new
    @page_title = "Add New Author"
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)
    if @author.save
      flash[:notice] = "Author created"
      redirect_to authors_path
    else
      render 'new'
    end
  end

  def index
    @authors = Author.all
  end

  def edit
    @author = Author.find(params[:id])
  end

  def update
    @author = Author.find(params[:id])
    @author.update(author_params)
    flash[:notice] = "Author's details updated"
    redirect_to authors_path
  end

  def destroy
    @author = Author.find(params[:id])
    @author.destroy
    flash[:notice] = "Author's details removed"
    redirect_to authors_path
  end




  private
    def author_params
      params.require(:author).permit(:first_name, :last_name)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @page_title = "Add Book"
    @book = Book.new
    @category = Category.new
    @author = Author.new
    @publisher = Publisher.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "Book Added"
      redirect_to books_path
    else
      render 'new'
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] ="Book Updated"
      redirect_to books_path
    else
      render 'edit'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    flash[:notice] = "Book Removed" 
    redirect_to books_path
  end

  def index
    @books = Book.all
    @categories = Category.all
  end

  def show
    @book = Book.find(params[:id])
    @categories = Category.all
  end

  private
    def book_params
      params.require(:book).permit(:title, :category_id, :author_id, :publisher_id, :isbn, :buy, :price, :format, :excerpt, :pages, :year, :coverpath)
    end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
    @page_title = "Add New Category"
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    # if @category.save
    #   redirect_to categories_path
    # else
    #   redirect_to new_category_path
    # end
    if @category.save
     flash[:notice] = "Category Created"
     redirect_to categories_path
   else
      render 'new'
   end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    @category.update(category_params)
    flash[:notice] = "Category Updated"
    redirect_to categories_path
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    flash[:notice] = "Category Removed" 
    redirect_to categories_path
  end

  def index  
     @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @categories = Category.all
    @books = @category.books
  end

  private
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  def new
    @page_title = "Add New Publisher"
    @publisher = Publisher.new
  end

  def create
    @publisher = Publisher.new(publisher_params)
    if @publisher.save
      flash[:notice] = "Publisher Created"
      redirect_to publishers_path
    else
      render 'new'
    end
  end


  def edit
    @publisher = Publisher.find(params[:id])
  end

  def update
    @publisher = Publisher.find(params[:id])
    @publisher.update(publisher_params)
    flash[:notice] = "Publisher's details updated"
    redirect_to publishers_path
  end

  def destroy
    @publisher = Publisher.find(params[:id])
    @publisher.destroy
    flash[:notice]="Publisher removed from the list"
    redirect_to publishers_path
  end

  def index
    @publishers = Publisher.all
  end

  private
    def publisher_params
      params.require(:publisher).permit(:name)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
	def full_name(author)
		author.first_name + ' ' + author.last_name
	end
end

app/helpers/books_helper.rb
module BooksHelper

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/views/about/index.html.erb
<h1><%= @page_title %></h1>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed velit dui, lobortis eu sagittis ut, bibendum non est. Sed nec vulputate tortor. Morbi at ornare augue. Pellentesque et massa ligula. Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur dapibus eu justo ac eleifend. Phasellus finibus massa nisl, sed hendrerit metus accumsan nec.</p>
<p>Mauris eu lorem vitae arcu finibus placerat sed sit amet massa. Nullam porttitor nibh ac sapien pellentesque, egestas commodo sapien tempor. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio risus. Maecenas mauris tortor, ultricies quis euismod ac, porta eget ipsum. Proin gravida ante sit amet ipsum aliquam vehicula. Suspendisse malesuada ex eu pulvinar hendrerit. Mauris quis ante facilisis, pharetra urna vel, semper dui.</p>

app/views/authors/create.html.erb
<h1>Authors#create</h1>
<p>Find me in app/views/authors/create.html.erb</p>

app/views/authors/destroy.html.erb
<h1>Authors#destroy</h1>
<p>Find me in app/views/authors/destroy.html.erb</p>

app/views/authors/edit.html.erb
<h2>Edit Author's Details</h2>

<%= form_for @author do |f| %>
	<!-- Check for errors -->
	<% if @author.errors.any? %>
		<% @author.errors.full_messages.each do |msg| %>
			<!-- Show errors -->
			<div class="alert alert-danger"><%= msg %></div>
		<% end%>
	<% end %>	
	<div class="form-group">
		<%= f.label :first_name %>:<br/>
		<%= f.text_field :first_name, class: 'form-control' %><br/>
	</div>

	<div class="form-group">
		<%= f.label :last_name %>:<br/>
		<%= f.text_field :last_name, class: 'form-control' %><br/>
	</div>
	<%= f.submit "Submit", class:'btn btn-primary' %>
	<%= link_to "Cancel", authors_path, class:'btn btn-default' %>
<% end %>

app/views/authors/index.html.erb
<h2>Authors' List</h2>

<table class="table table-striped">
	<tr>
		<th>Author's Name</th>
		<th>Action</th>
	</tr>	

	<% @authors.each do |author| %>
		<tr>
			<td><%= full_name(author) %></td>
			<td><%= link_to 'Edit', edit_author_path(author.id) %> | <%= link_to 'Delete',author_path(author), method: :delete, data: {confirm: "Are you sure you want to delete this author?"}%></td>
		</tr>
	<% end %>
</table>

app/views/authors/new.html.erb
<h2>Add New Author</h2>

<%= form_for @author do |f| %>
	<!-- Check for errors -->
	<% if @author.errors.any? %>
		<% @author.errors.full_messages.each do |msg| %>
			<!-- Show errors -->
			<div class="alert alert-danger"><%= msg %></div>
		<% end%>
	<% end %>	
	<div class="form-group">
		<%= f.label :first_name %>:<br/>
		<%= f.text_field :first_name, class: 'form-control' %><br/>
	</div>

	<div class="form-group">
		<%= f.label :last_name %>:<br/>
		<%= f.text_field :last_name, class: 'form-control' %><br/>
	</div>
	<%= f.submit "Submit", class:'btn btn-primary' %>
	<%= link_to "Cancel", authors_path, class:'btn btn-default' %>
<% end %>

app/views/authors/show.html.erb
<h1>Authors#show</h1>
<p>Find me in app/views/authors/show.html.erb</p>

app/views/authors/update.html.erb
<h1>Authors#update</h1>
<p>Find me in app/views/authors/update.html.erb</p>

app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/books/edit.html.erb
<h2>Edit <%= @book.title %></h2>
<%= form_for @book do |f| %>
	<% if @book.errors.any? %>
		<% @book.errors.full_messages.each do |msg| %>
			<!-- Show errors -->
			<div class="alert alert-danger"><%= msg %></div>
		<% end%>
	<% end %>	
	<div class="form-group">
		<%= f.label :title %><br/>
		<%= f.text_field :title, class: 'form-control' %><br/>
	</div>

	<div class="form-group">
		<%= f.label :isbn %><br/>
		<%= f.text_field :isbn, class: 'form-control' %><br/>
	</div>

	<div class="form-group">
		<%= f.label :category %><br/>
		<%= f.select :category_id, Category.all.collect {|x| [x.name, x.id]}, {:include_blank => "Select One"},class: 'form-control' %><br/>
	</div>

	<div class="form-group">
		<%= f.label :author %><br/>
		<%= f.select :author_id, Author.all.collect {|x| [x.first_name + ' ' + x.last_name, x.id]}, {:include_blank => "Select One"},class: 'form-control' %><br/>
	</div>

	<div class="form-group">
		<%= f.label :publisher %><br/>
		<%= f.select :publisher_id, Publisher.all.collect {|x| [x.name, x.id]}, {:include_blank => "Select One"},class: 'form-control' %><br/>
	</div>

	<div class="form-group">
		<%= f.label :year%><br/>
		<%= f.text_field :year, class:'form-control' %><br/>
	</div>

	<div class="form-group">
		<%= f.label :coverpath %><br/>
		<%= f.text_field :coverpath, class:'form-control' %><br/>
	</div>


	<div class="form-group">
		<%= f.label :format %><br/>
		<%= f.text_field :format, class:'form-control' %><br/>
	</div>

	<div class="form-group">
		<%= f.label :excerpt %><br/>
		<%= f.text_area :excerpt, class:'form-control' %><br/>
	</div>

	<div class="form-group">
		<%= f.label :pages %><br/>
		<%= f.number_field :pages, class:'form-control' %><br/>
	</div>

	<div class="form-group">
		<%= f.label :price %><br/>
		<%= f.text_field :price, class:'form-control' %><br/>
	</div>

	<div class="form-group">
		<%= f.label :buy %><br/>
		<%= f.text_field :buy, class:'form-control' %><br/>
	</div>

	<%= f.submit "Submit", class:'btn btn-primary' %>
	<%= link_to "Cancel", books_path, class:'btn btn-default' %>
<%end %>

app/views/books/index.html.erb
<div id="books-index">
<% @books.each_slice(4) do |book| %>
	<div class="row">
		<% book.each do |book| %>
			<div class="col-md-3 col-sm-3">
				<h3><%= book.title %></h3>
				<%= image_tag(book.coverpath)%>
				<%= link_to "Read More", book_path(book), class:"btn btn-primary" %>
			</div>
		<% end %>
	</div>
<% end %>
</div>

app/views/books/new.html.erb
<h2>Add New Book</h2>
<%= form_for @book do |f| %>
	<% if @book.errors.any? %>
		<% @book.errors.full_messages.each do |msg| %>
			<!-- Show errors -->
			<div class="alert alert-danger"><%= msg %></div>
		<% end%>
	<% end %>	
	<div class="form-group">
		<%= f.label :title %><br/>
		<%= f.text_field :title, class: 'form-control' %><br/>
	</div>

	<div class="form-group">
		<%= f.label :isbn %><br/>
		<%= f.text_field :isbn, class: 'form-control' %><br/>
	</div>

	<div class="form-group">
		<%= f.label :category %><br/>
		<%= f.select :category_id, Category.all.collect {|x| [x.name, x.id]}, {:include_blank => "Select One"},class: 'form-control' %><br/>
	</div>

	<div class="form-group">
		<%= f.label :author %><br/>
		<%= f.select :author_id, Author.all.collect {|x| [x.first_name + ' ' + x.last_name, x.id]}, {:include_blank => "Select One"},class: 'form-control' %><br/>
	</div>

	<div class="form-group">
		<%= f.label :publisher %><br/>
		<%= f.select :publisher_id, Publisher.all.collect {|x| [x.name, x.id]}, {:include_blank => "Select One"},class: 'form-control' %><br/>
	</div>

	<div class="form-group">
		<%= f.label :year%><br/>
		<%= f.text_field :year, class:'form-control' %><br/>
	</div>

	<div class="form-group">
		<%= f.label :coverpath %><br/>
		<%= f.text_field :coverpath, class:'form-control' %><br/>
	</div>


	<div class="form-group">
		<%= f.label :format %><br/>
		<%= f.text_field :format, class:'form-control' %><br/>
	</div>

	<div class="form-group">
		<%= f.label :excerpt %><br/>
		<%= f.text_area :excerpt, class:'form-control' %><br/>
	</div>

	<div class="form-group">
		<%= f.label :pages %><br/>
		<%= f.number_field :pages, class:'form-control' %><br/>
	</div>

	<div class="form-group">
		<%= f.label :price %><br/>
		<%= f.text_field :price, class:'form-control' %><br/>
	</div>

	<div class="form-group">
		<%= f.label :buy %><br/>
		<%= f.text_field :buy, class:'form-control' %><br/>
	</div>

	<%= f.submit "Submit", class:'btn btn-primary' %>
	<%= link_to "Cancel", books_path, class:'btn btn-default' %>
<%end %>

app/views/books/show.html.erb
<div id="books-show">
	
	<h2><%= @book.title %></h2>
	<div class="books-show-left">
		<%= image_tag(@book.coverpath)%>
	</div>
	<div class="book-show-right">
		<h3>Book Info:</h3>
		<ul>
			<li><strong>Category: </strong><%= @book.category.name %></li>
			<li><strong>Author: </strong><%= full_name(@book.author) %></li>
			<li><strong>Publisher: </strong><%= @book.publisher.name %></li>
			<li><strong>Year: </strong><%= @book.year %></li>
			<li><strong>ISBN: </strong><%= @book.isbn %></li>
			<li><strong>Format: </strong><%= @book.format %></li>
			<li><strong>Pages: </strong><%= @book.pages%></li>
		</ul>
		<%= link_to "Buy for " + @book.price, @book.buy, class:'btn btn-success', target:'_blank'%>
	</div>
	<div class="clearfix"></div>
	<h4>Excerpt:</h4>
	<p><%= @book.excerpt %></p>

	<h3>Admin Functions</h3>
	<%= link_to 'Edit', edit_book_path(@book) %> | <%= link_to 'Delete', book_path(@book), method: :delete, data: {confirm: "Are you sure?"} %> | <%= link_to 'Back', books_path %> 
</div>

app/views/books/update.html.erb
<h1>Books#update</h1>
<p>Find me in app/views/books/update.html.erb</p>

app/views/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

app/views/categories/destroy.html.erb
<h1>Categories#destroy</h1>
<p>Find me in app/views/categories/destroy.html.erb</p>

app/views/categories/edit.html.erb
<h2>Edit Category</h2>

<%= form_for @category do |f| %>
	<!-- Check for errors -->
	<% if @category.errors.any? %>
		<% @category.errors.full_messages.each do |msg| %>
			<!-- Show errors -->
			<div class="alert alert-danger"><%= msg %></div>
		<% end%>
	<% end %>
	<div class="form-group">
		<%= f.label :name %><br/>
		<%= f.text_field :name, class: 'form-control' %><br/>
	</div>
	<%= f.submit "Submit", class:'btn btn-primary' %>
	<%= link_to "Cancel", categories_path, class:'btn btn-default' %>
<% end %>

app/views/categories/index.html.erb
<h2>Categories</h2>

<table class="table table-striped">
	<tr>
		<th>Category Name</th>
		<th>Action</th>
	</tr>	

	<% @categories.each do |category| %>
		<tr>
			<td><%= category.name %></td>
			<td><%= link_to 'Edit', edit_category_path(category.id) %> | <%= link_to 'Delete',category_path(category), method: :delete, data: {confirm: "Are you sure you want to delete this category?"}%></td>
		</tr>
	<% end %>
</table>

app/views/categories/new.html.erb
<h2>Add New Category</h2>

<%= form_for @category do |f| %>
	<!-- Check for errors -->
	<% if @category.errors.any? %>
		<% @category.errors.full_messages.each do |msg| %>
			<!-- Show errors -->
			<div class="alert alert-danger"><%= msg %></div>
		<% end%>
	<% end %>
	<div class="form-group">
		<%= f.label :name %><br/>
		<%= f.text_field :name, class: 'form-control' %><br/>
	</div>
	<%= f.submit "Submit", class:'btn btn-primary' %>
	<%= link_to "Cancel", categories_path, class:'btn btn-default' %>
<% end %>

app/views/categories/show.html.erb
<h2><%= @category.name %></h2>
<div id="books-index">
<% @books.each_slice(4) do |book| %>
	<div class="row">
		<% book.each do |book| %>
			<div class="col-md-3 col-sm-3">
				<h3><%= book.title %></h3>
				<%= image_tag(book.coverpath)%>
				<%= link_to "Read More", book_path(book), class:"btn btn-primary" %>
			</div>
		<% end %>
	</div>
<% end %>
</div>

app/views/categories/update.html.erb
<h1>Categories#update</h1>
<p>Find me in app/views/categories/update.html.erb</p>

app/views/layouts/_alert.html.erb
<!-- ALERT and MESSAGES -->

<% if flash[:notice]  %>
	<div class="alert alert-success"><%=flash[:notice]%></div>
<% end %>

<% if flash[:alert] %>
	<div class="alert alert-danger"><%=flash[:alert]%></div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
	<div class="container">
		<p>Copyright &copy; 2015 All Rights Reserved </p>
	</div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="<%= params[:controller]=="books" ? 'active' : ' ' %>"><%= link_to "Home", root_path %></li>
        <li class="<%= params[:controller]=="about" ? 'active' : ' ' %>"><%= link_to "About", about_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Add New<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Book", new_book_path %></li>
              <li><%= link_to "Category", new_category_path %></li>
              <li><%= link_to "Author", new_author_path %></li>
              <li><%= link_to "Publisher", new_publisher_path %></li>
            </ul>
        </li>

        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Manage<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Categories", categories_path %></li>
              <li><%= link_to "Authors", authors_path %></li>
              <li><%= link_to "Publishers", publishers_path %></li>
            </ul>
        </li>

      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

<header>
  <div class="container header">
    <h1>The Bookstore <small><%= @page_title ? @page_title : "Welcome" %></small></h1>
  </div>
</header>

app/views/layouts/_sidebar.html.erb
<div class="sidebar-content">
	<% if params[:controller] == 'about' %>
	<div class="well">
		<h3>Location</h3>
		<ul>
			<li>The Bookstore</li>
			<li>499 Massachusetts Ave, Unit 2</li>
			<li>Boston, MA 02110</li>
			<li>Phone: (617) 555-5555</li>
			<li>Email: support@thebookstore.com</li>
		</ul>
	</div>
	<% end %>

	<% if params[:controller] == 'books' && params[:action] == 'index' || params[:action] == 'show' %>
		<div class="list-group">
		<% @categories.each do |category| %>
			<%= link_to category.name, category_path(category.id), class:"list-group-item" %>
		<% end %>	
		</div>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @page_title ? @page_title : "Welcome to" %> | The Bookstore</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
</head>
<body>
	<%=render 'layouts/header' %>
	<section>
		<div class="container content">
			<div class="row">
				<div class="col-md-8">
				<%= render 'layouts/alert' %>
					<%= yield %>
				</div>

				<div class="col-md-4">
					<%=render 'layouts/sidebar' %>
				</div>
			</div>

		</div>
	</section>
	<%= render 'layouts/footer' %>
</body>
</html>

app/views/publishers/create.html.erb
<h1>Publishers#create</h1>
<p>Find me in app/views/publishers/create.html.erb</p>

app/views/publishers/destroy.html.erb
<h1>Publishers#destroy</h1>
<p>Find me in app/views/publishers/destroy.html.erb</p>

app/views/publishers/edit.html.erb
<h2>Edit Publisher</h2>

<%= form_for @publisher do |f| %>
	<!-- Check for errors -->
	<% if @publisher.errors.any? %>
		<% @publisher.errors.full_messages.each do |msg| %>
			<!-- Show errors -->
			<div class="alert alert-danger"><%= msg %></div>
		<% end%>
	<% end %>	
	<div class="form-group">
		<%= f.label :name %><br/>
		<%= f.text_field :name, class: 'form-control' %><br/>
	</div>
	<%= f.submit "Submit", class:'btn btn-primary' %>
	<%= link_to "Cancel", publishers_path, class:'btn btn-default' %>
<% end %>

app/views/publishers/index.html.erb
<h2>Publishers</h2>

<table class="table table-striped">
	<tr>
		<th>Publisher's Name</th>
		<th>Action</th>
	</tr>	

	<% @publishers.each do |publisher| %>
		<tr>
			<td><%= publisher.name %></td>
			<td><%= link_to 'Edit', edit_publisher_path(publisher.id) %> | <%= link_to 'Delete',publisher_path(publisher), method: :delete, data: {confirm: "Are you sure you want to delete this publisher?"}%></td>
		</tr>
	<% end %>
</table>

app/views/publishers/new.html.erb
<h2>Add New Publisher</h2>

<%= form_for @publisher do |f| %>
	<!-- Check for errors -->
	<% if @publisher.errors.any? %>
		<% @publisher.errors.full_messages.each do |msg| %>
			<!-- Show errors -->
			<div class="alert alert-danger"><%= msg %></div>
		<% end%>
	<% end %>	
	<div class="form-group">
		<%= f.label :name %><br/>
		<%= f.text_field :name, class: 'form-control' %><br/>
	</div>
	<%= f.submit "Submit", class:'btn btn-primary' %>
	<%= link_to "Cancel", publishers_path, class:'btn btn-default' %>
<% end %>

app/views/publishers/update.html.erb
<h1>Publishers#update</h1>
<p>Find me in app/views/publishers/update.html.erb</p>